### PR TITLE
[Issue #1] Add Google Authentication

### PR DESCRIPTION
**Pull request by Andretalik**
#### What does this PR do?
This adds the functionality allowing a user to login to the CKAN Data Platform using their owned Google account.
#### Description of Task to be completed?
The task was to add functionality allowing the login to happen, as well as add the button to the login page.
#### How should this be manually tested?
This can be tested in two ways.
 - Clone the repo and run nosetests
 - Trigger a build on TravisCI.
#### Any background context you want to provide?
Before a user needed to put in their email address and set a password before they could access some features of the Data Platform.
#### What are the relevant pivotal tracker stories?
N/A
#### Screenshots (if appropriate)
screen shot 2017-10-09 at 9 33 53 am

### CODE REVIEW

**Comment by DavidLemayian** [comment]
@Andretalik This is looking good. Thanks for sending. Could we have the Social login come below CKAN's own?

Also, I haven't checked thoroughly but if I already have an e-mail account, does it connect the two together?

**Comment by Andretalik** [comment]
@DavidLemayian 
I am not entirely sure what you mean by connecting your accounts if you have an email address. Do you mean if you already have a CKAN account created using your Google account and want to login using the Google login it connects the two accounts since they have the same email address?


It does not connect the two accounts. Rather it creates a CKAN account for you using your Google credentials, but it also uses the Google cookies hence as long as you are logged into Google it automates the login process for the user.

**Comment by Andretalik** [comment]
@DavidLemayian 
I will move the Social Login to be below CKAN's own.

**Comment by Andretalik** [comment]
All the work on this branch has been incorporated into the 1a-add_github_auth branch and is present there.
As a result, this PR is unnecessary.
Due to this, I will close it without merging.

**Pull request closed without merging**
